apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: error-rate
spec:
  description: Fraction of requests with error responses
  params:
  - name: query
    value: |
      (sum(increase(istio_requests_total{response_code=~'5..',reporter='source',destination_workload='$version',destination_workload_namespace='$namespace'}[${elapsedTime}s])) or on() vector(0)) / (sum(increase(istio_requests_total{reporter='source',destination_workload='$version',destination_workload_namespace='$namespace'}[${elapsedTime}s])) or on() vector(0))
  type: Gauge
  sampleSize: request-count
  provider: prometheus
  jqExpression: ".data.result[0].value[1] | tonumber"
  urlTemplate: http://prometheus-operated.iter8-system:9090/api/v1/query
