# This cluster role enables manipulation of KFServing inferenceservices
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: isvc-reader-writer
rules:
- apiGroups:
  - serving.kubeflow.org
  resources:
  - inferenceservices
  verbs:
  - get
  - list
  - patch
  - update
---
# This cluster role enables manipulation of Istio virtual services
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vs-reader-writer
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - get
  - list
  - patch
  - update
